env:
  es2021: true
  node: true
extends:
  - standard
  - plugin:github/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules: {}
